# Generated by Django 4.1.13 on 2024-11-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='school_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
