# Generated by Django 4.1.13 on 2024-11-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_subjects',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='study_type',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid')], max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_bio',
            field=models.TextField(blank=True),
        ),
    ]
