# Generated by Django 4.1.13 on 2024-11-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_connectionrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionrequests',
            name='chatroomname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
