# Generated by Django 4.1.13 on 2024-11-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_connectionrequests_chatroomname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('timestamp',)},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='date_added',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='message',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='message',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
