# Generated by Django 4.1.13 on 2024-11-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_message_file_alter_message_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
